apiVersion: apps/v1
kind: Deployment
metadata:
  name: exo5kub-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: exo5kub-app
  template:
    metadata:
      labels:
        app: exo5kub-app
    spec:
      volumes: 

        - name: firstvol-hostpath 
          hostPath: 
            path: /data 
            type: DirectoryOrCreate 

      containers: 
      - name: exo5-app
        volumeMounts:

          - mountPath: /app/story
            name: firstvol-hostpath

        image: nancylence/exo5-kub:latest
        env: 
          - name: STORY_FOLDER 
            value: story 

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
